#! /usr/bin/env bash
set -e

export LD_PRELOAD="/usr/lib/x86_64-linux-gnu/libtcmalloc.so.4"
export TCMALLOC_RELEASE_RATE=10
export VISION_HOME="/data/vision"
export CONFIGHOME="$VISION_HOME/configs"
export DATABASEHOME="$VISION_HOME/output-directory"
export NETWORK="standalone"

function main() {
  echo ""
  echo "Starting Vision Quickstart"
  echo ""
  echo "network: standalone"
  echo ""

  copy_defaults

  exec_service
}

function copy_defaults() {
  local CP="cp -a"

  if [ -d $CONFIGHOME ]; then
    echo "vision-core: config directory exists, skipping copy."
  else
    mkdir -p $CONFIGHOME
    if [[ -z "$CONFIG_FILENAME" ]];then
      $CP /opt/vision/"${NETWORK}"/configs/template.config $CONFIGHOME/"${NETWORK}".config
    fi
  fi
}

function exec_service() {
  echo "RUNNING...$NETWORK"
  /usr/bin/java -Xmx12g -XX:+UseConcMarkSweepGC -jar /opt/vision/FullNode.jar -c $CONFIGHOME/"${NETWORK}".config --log-config /data/vision/logs/ --witness
}
main
